spring:
  datasource:
    dynamic:
      primary: debut-tools
      datasource:
        debut-tools:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.12:3306/debug-tools?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&
          username: root
          password: 123456Aa
  application:
    name: testSpringApplication
  profiles:
    active: default
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.future0923.debug.tools.test.spring.boot.mybatis.model